# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  release:
    types: [ "published" ]
  workflow_dispatch:
  

jobs:
  build:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./MelonWebApi.csproj
      working-directory: ./Code/MelonWebApi
    - name: Build
      run: dotnet build -c Release --no-restore ./MelonWebApi.csproj
      working-directory: ./Code/MelonWebApi
    - name: Tarball
      working-directory: ./Code/MelonWebApi/bin/Release/net8.0/
      run: tar -czvf 1.0.68.843.tar.gz *
    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.9.0
      with: 
        file: 1.0.68.843.tar.gz
            

